### PR TITLE
replace Raphael's grammar with Boris' grammar

### PR DESCRIPTION
**Pull request by thorade**
Opening this Pull Request so we can have discussion about it.
Please merge only once discussion has finished.

Boris' grammar seems to be working more reliable, so I think we should use it as a starting point.
Someone who understands these grammars should then add everything back that was better in Raphael's grammar.

For comparison, we can use Lightshow and some large packages from the MSL:
- MSL R134a: [v0.2.1](http://bit.ly/1jshJys) versus [BorisGrammar](http://bit.ly/1OxaWAh)
- annotation pre semicolon: [v0.2.1](http://bit.ly/1RM2qMa) versus [BorisGrammar](http://bit.ly/1Kbe397)

### CODE REVIEW

**Comment by thorade** [comment]
Boris' grammar is also not completly error free, so if we decide to merge this PR then we would have to fix the same issues that are present in Boris' issue tracker:
https://github.com/BorisChumichev/modelicaSublimeTextPackage/issues

**Comment by tshort** [comment]
I'm good with merging this. I tried several files. I found one case where @BorisChumichev's grammar is wrong:

http://bit.ly/1PuWY19

Annotations are tricky to get right. Some options for fixing this one are:
1. Make the regex look for a trailing `);` instead of just `;`.
2. Have the grammar look for nested `Icon(` -- `)`. I think that's how Boris avoids tagging semicolons in the HTML section.

**Comment by thorade** [comment]
Is that fix sufficient? 
Does it work if the annotation ends with `) ;` (note the space between parantheses and semicolon)?

**Comment by tshort** [comment]
Here's what was in the original grammar:

```
'\\)\\s*;\\s*$'
```

**Comment by thorade** [comment]
OK, that line is reverted to Raphael's version.
http://bit.ly/1LvqD8O

**Comment by thorade** [comment]
@lochel if it looks good to you also, feel free to press the Merge button.

**Comment by thorade** [comment]
Here is another case where Raphael's grammar works better:
http://bit.ly/1GeI3G1 versus http://bit.ly/1RJZD6j
but I don't know how to fix it.
Probably `enumeration` should appear as keyword somewhere in the grammar file!?

**Comment by tshort** [comment]
I think this can be merged. The issues with Boris' grammar can be added separately.

**Comment by thorade** [comment]
Merged the PR and published a new minor version.
I will close some of the issues and open new ones this weekend.

**Pull request merged**
