### PR TITLE
Adapt coding style to modelica.cson

### PR DESCRIPTION
**Pull request by lochel**
I think we should use the same coding style for modelica.cson and modelicascript.cson.

### CODE REVIEW

**Comment by thorade** [comment]
This is doing two things: 
- replace all single quotes with double quotes
- use less spaces for indentation

No changes to the content / no functional changes, correct? Then you can just merge it.

**Comment by thorade** [comment]
One more comment: If you change a lot of whitespace, then it is good practice to put all the whitespace changes in one commit and everything else in another (or mutliple other) commits. Then it becomes a bit easier to see what happened.
Related: Ignore Whitepsace in the diff by appending **`?w=1`** to the commit URL:
https://github.com/lochel/atom-language-modelica/commit/a154876f14914335d476fa5368c26c31bcb9312c?w=1

https://github.com/blog/967-github-secrets

**Comment by lochel** [comment]
@thorade good hint, thanks.

**Comment by bilderbuchi** [comment]
btw this works on many github pages, e.g. [this PRs diff view](https://github.com/modelica-tools/atom-language-modelica/pull/24/files?w=1)

**Pull request merged**
