### PR TITLE
Fix syntax highlighting

### PR DESCRIPTION
**Pull request by lochel**
Adapt syntax highlighting according to SimplyDanny/modelica-language-vscode#3. I haven’t tested this with atom yet.

### CODE REVIEW

**Comment by bilderbuchi** [comment]
Do you have a test string/model that can be used with lighthouse to check the bug you found & fixed?

**Comment by lochel** [comment]
Sure, sorry for the lazy description. It is about the following kind of patterns:
`Foo.Bar(foo2.bar2("foo bar"));`

Now, I have also tested it with atom and it looks good.

**Comment by lochel** [comment]
This is the bug: [link](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fmodelica-tools%2Fatom-language-modelica%2Fmaster%2Fgrammars%2Fmodelica.cson&grammar_text=&code_source=from-text&code_url=&code=Foo.Bar%28foo2.bar2%28%22foo+bar%22%29%29%3B)
And this is how it should look like: [link](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Flochel%2Fatom-language-modelica%2Fsyntax%2Fgrammars%2Fmodelica.cson&grammar_text=&code_source=from-text&code_url=&code=Foo.Bar%28foo2.bar2%28%22foo+bar%22%29%29%3B)

**Comment by bilderbuchi** [comment]
Thank you!

**Comment by thorade** [comment]
Looks good to me. Should I merge it and publish a patch release?

**Comment by lochel** [comment]
Yes, I think this can be merged.

**Pull request merged**
